<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/**
 * Class User
 *
 * Represents an authenticated user (landlord or property manager) who owns
 * properties, rooms, renters, and lease agreements.
 *
 * @package App\Models
 */
class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    /**
     * Get all properties managed by the user.
     *
     * @return HasMany
     */
    public function properties(): HasMany
    {
        return $this->hasMany(Property::class);
    }

    /**
     * Get all rooms across all properties owned by the user.
     *
     * @return HasManyThrough
     */
    public function rooms(): HasManyThrough
    {
        return $this->hasManyThrough(Room::class, Property::class);
    }

    /**
     * Get all renters managed by the user.
     *
     * @return HasMany
     */
    public function renters(): HasMany
    {
        return $this->hasMany(Renter::class);
    }

    /**
     * Get all leases created by or belonging to the user's renters.
     *
     * @return HasManyThrough
     */
    public function leases(): HasManyThrough
    {
        return $this->hasManyThrough(Lease::class, Renter::class);
    }

    /**
     * Get all invoices generated by the user.
     *
     * @return HasMany
     */
    public function invoices(): HasMany
    {
        return $this->hasMany(Invoice::class);
    }
}
