<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/**
 * Class User
 *
 * Represents an authenticated user in RoomsForRent (Superadmin or Landlord).
 *
 * @package App\Models
 */
class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory, Notifiable;

    /**
     * Role definitions.
     */
    public const ROLE_SUPERADMIN = 'superadmin';
    public const ROLE_LANDLORD = 'landlord';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    /*
    |--------------------------------------------------------------------------
    | Role Helper Methods
    |--------------------------------------------------------------------------
    */

    /**
     * Check if the user is a Superadmin.
     */
    public function isSuperAdmin(): bool
    {
        return $this->role === self::ROLE_SUPERADMIN;
    }

    /**
     * Check if the user is a Landlord.
     */
    public function isLandlord(): bool
    {
        return $this->role === self::ROLE_LANDLORD;
    }

    /*
    |--------------------------------------------------------------------------
    | Relationships (Landlord-scoped)
    |--------------------------------------------------------------------------
    */

    /**
     * Get all properties managed by the landlord.
     *
     * @return HasMany
     */
    public function properties(): HasMany
    {
        return $this->hasMany(Property::class);
    }

    /**
     * Get all rooms across all properties owned by the landlord.
     *
     * @return HasManyThrough
     */
    public function rooms(): HasManyThrough
    {
        return $this->hasManyThrough(Room::class, Property::class);
    }

    /**
     * Get all renters managed by the landlord.
     *
     * @return HasMany
     */
    public function renters(): HasMany
    {
        return $this->hasMany(Renter::class);
    }

    /**
     * Get all leases created by or belonging to the landlord's renters.
     *
     * @return HasManyThrough
     */
    public function leases(): HasManyThrough
    {
        return $this->hasManyThrough(Lease::class, Renter::class);
    }

    /**
     * Get all invoices generated by the landlord.
     *
     * @return HasMany
     */
    public function invoices(): HasMany
    {
        return $this->hasMany(Invoice::class);
    }
}
